### ISSUE TITLE
在运行程序时出现如下问题？不知道怎么解决

### ISSUE THREAD

**Issue by teenager-debug** [weichihuab/ML_B-C-N#1]
Traceback (most recent call last):
  File "E:/python files/B_C_N/rf_bulk_modulus.py", line 76, in <module>
    feature_list.append(fg.features_generator(data[i]["full_formula"]))
  File "E:\python files\B_C_N\includes\features_gen.py", line 124, in features_generator
    s_val.append(int(str1[1:pos2]))
ValueError: invalid literal for int() with base 10: 'up>14</sup>'

**Comment by weichihuab** [comment]
It's likely the Error is due to a different version of pymatgen. Could you please check if you're using pymatgen-2021.2.16? Thanks!

**Comment by teenager-debug** [comment]
Thank you very much! After upgrading the version of pymatgen, the program can  run normally.
